const lastname="Stein";
console.log(lastname);
console.log(typeof lastname);
const number=20;
console.log(number);
console.log(typeof number);
const isActive=true;
console.log(isActive);
console.log(typeof isActive);
const phone=undefined;
console.log(phone);
console.log(typeof phone);
const object=null;
console.log(object);
console.log(typeof object);
let a='gggg';
console.log(a);
let b=`vghj`;
console.log(b);
console.log('hello '+name);
console.log(`hello ${name}`);
console.log(2+'2');
console.log(2+'2'+2);
console.log(2+2+'2');
console.log(String(2));
let y=String(true);
console.log(y);
console.log(typeof y);
y=Number('2');
console.log(y);
console.log(typeof y);
y=Number(false);
console.log(y);
console.log(typeof y);